version: "3.8"

services:
  pnl-solana-tool-service:
    container_name: pnl-solana-tool
    image: pnl-solana-tool
    build:
      context: .
      dockerfile: Dockerfile
    hostname: pnl-solana-tool
    restart: always
    networks:
      - pnl-solana-tool-network
    command: ["sh", "-c", "cd build/execute && ./server"]
    volumes:
      - .:/build
    ports:
      - 9000:9000
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo:
    image: mongo:latest
    container_name: mongo-db
    hostname: mongodb
    networks:
      - pnl-solana-tool-network
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    depends_on:
      - pnl-solana-tool-service

networks:
  pnl-solana-tool-network:
    name: pnl-solana-tool-network
    driver: bridge