version: '3'

services:
  wso2is:
    image: wso2/wso2is:latest
    container_name: wso2is
    ports:
      - "9443:9443"
    environment:
      - USER=wso2user
      - PASS=wso2password
    volumes:
      - ./wso2is_repository:/home/wso2carbon/wso2is/repository/
    restart: always